# Generated by Django 5.2.8 on 2025-11-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('retail_price', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['retail_price'], name='routing_fue_retail__e50bf6_idx')],
            },
        ),
    ]
